language: emacs-lisp
os:
  - linux
  - osx
addons:
  apt:
    update: true
    sources:
      ubuntu-elisp
  homebrew:
    packages:
      - cask
    update: true
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
env:
  - EMACS=emacs25
  - EMACS=emacs-snapshot
before_install:
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
script:
  - emacs --version
  - make update
  - make test
