language: emacs-lisp
os:
  - linux
  - osx
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
      - python
      - emacs-nox
  homebrew:
    packages:
      - cask
      - emacs
    update: true
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
before_install:
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
script:
  - emacs --version
  - make update
  - make test
